esphome:
  name: wemosd1mini-bedroom

esp8266:
  board: d1_mini

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
  password: "60c7411d9b95d6cd93bda7be51cb503a"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Wemosd1Mini-Bedroom"
    password: "y7o4W3zitscf"

captive_portal:

i2c:
  sda: 4
  scl: 5
  scan: true
#  id: bus_a
  
dallas:
  - pin: 0
    update_interval: 60s

binary_sensor:
  - platform: status
    name: power
  
sensor:
  - platform: bmp280
    temperature:
      name: "bmp280_temperature"
      oversampling: 16x
    pressure:
      name: "bmp280_pressure"
      unit_of_measurement: "мм рт.ст."
      filters:
        - multiply: 0.75006375541921
    address: 0x76
    update_interval: 60s
  
  - platform: dallas
    address: 0x2c3c01f095e74b28
    name: "dallas_temperature"
    filters:
      - filter_out: nan

  - platform: dht
    pin: 2
    temperature:
      name: "dht22_temperature"
    humidity:
      name: "dht22_humidity"
    update_interval: 60s
